name = "delivery-scheduler-server"
main = "worker-server.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "DELIVERY_DATA"
id = "a9db3bd06ff84ac087a712ac4406447a"

[site]
bucket = "./dist"
